# Replace these values for your dev environment.
flyway.url=jdbc:postgresql://accountlink-dev-databaseb269d8bb-f32ocp35prtl.cluster-cdcaamdrt4pw.us-east-1.rds.amazonaws.com:5432/accountlink
flyway.user=accountlink
#flyway.password=env_var
flyway.locations=filesystem:./migrations
flyway.schemas=public
flyway.defaultSchema=public
