# Replace these values for your dev environment.
flyway.url=jdbc:postgresql://REPLACE_ME_HOST:5432/accountlink
flyway.user=REPLACE_ME_USER
flyway.password=REPLACE_ME_PASSWORD
flyway.locations=filesystem:./migrations
flyway.schemas=public
flyway.defaultSchema=public
