name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./cmd/... ./internal/...

      - name: Run mutation tests
        run: |
          go install github.com/avito-tech/go-mutesting/cmd/go-mutesting@latest
          go-mutesting ./internal/app ./internal/domain/accountlink.go
